version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: db_vencidinhos
      MYSQL_USER: vencidinho
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: senha
    ports:
      - "3306:3306"